Repository WookieeMatt/Essence20, pull requests merged in 2023-04, with the labels that each got.

#345 Fixing initiative formula not updating
  module/dice.mjs
  module/essence20.mjs
Labels: bug

#355 Fix for the Is Specialized checkbox on the Initiative Roll.
  module/dice.mjs
Labels: bug

#356 Fixing item sheet label wrapping
  lang/en.json
  templates/item/parts/item-sheet-field.hbs
Labels: bug

#366 Fixing/unifying sheet and combat tracker initiative rolls
  lang/en.json
  module/dice.mjs
  module/dice.test.js
  module/documents/combat.mjs
  module/essence20.mjs
  module/sheets/actor-sheet.mjs
Labels: bug

#346 Skills reconfigure
  module/dice.mjs
  module/dice.test.js
  module/documents/item.mjs
  module/helpers/config.mjs
  module/migration.mjs
  module/sheets/actor-sheet.mjs
  system.json
  template.json
  templates/actor/parts/actor-accordion-skills.hbs
  templates/actor/parts/actor-essence-skills.hbs
  templates/actor/parts/actor-pc-skills.hbs
  templates/actor/parts/actor-spells.hbs
Labels: migration

#374 Roll dialog dependency injection to allow mocking
  module/dice.mjs
  module/dice.test.js
  module/documents/combat.mjs
  module/documents/item.mjs
  module/helpers/roll-dialog.mjs
  module/sheets/actor-sheet.mjs
Labels: tech debt

#379 Normalize upshift/shiftUp and downshift/shiftDown
  module/dice.mjs
  module/documents/item.mjs
  module/helpers/roll-dialog.mjs
  templates/actor/parts/actor-essence-skills.hbs
  templates/actor/parts/items/spell/container.hbs
Labels: tech debt

#378 Moving actor sheets into their own directory
  module/sheets/actor-sheet.mjs
  templates/actor/sheets/giJoe.hbs
  templates/actor/sheets/megaformZord.hbs
  templates/actor/sheets/npc.hbs
  templates/actor/sheets/pony.hbs
  templates/actor/sheets/powerRanger.hbs
  templates/actor/sheets/transformer.hbs
  templates/actor/sheets/vehicle.hbs
  templates/actor/sheets/zord.hbs
Labels: tech debt

#375 Moving `statusEffects` into config
  module/essence20.mjs
  module/helpers/config.mjs
Labels: tech debt

#385 Adding armor to Zords/MFZs
  lang/en.json
  templates/actor/parts/headers/actor-megaformZord-header.hbs
  templates/actor/parts/headers/actor-zord-header.hbs
Labels: power rangers

#380 Fixing Zord/MFZ console warnings
  module/migration.mjs
  template.json
  templates/actor/parts/actor-zord-common.hbs
Labels: bug, transformers, migration

#384 Move item templates
  module/helpers/templates.mjs
  module/sheets/item-sheet.mjs
  templates/item/item-threatPower-sheet.hbs
  templates/item/parts/active-effects.hbs
  templates/item/parts/description.hbs
  templates/item/parts/header.hbs
  templates/item/parts/sheet-field.hbs
  templates/item/sheets/altMode.hbs
  templates/item/sheets/armor.hbs
  templates/item/sheets/bond.hbs
  templates/item/sheets/classFeature.hbs
  templates/item/sheets/contact.hbs
  templates/item/sheets/feature.hbs
  templates/item/sheets/gear.hbs
  templates/item/sheets/hangUp.hbs
  templates/item/sheets/magicBauble.hbs
  templates/item/sheets/megaformTrait.hbs
  templates/item/sheets/origin.hbs
  templates/item/sheets/perk.hbs
  templates/item/sheets/power.hbs
  templates/item/sheets/specialization.hbs
  templates/item/sheets/spell.hbs
  templates/item/sheets/threatPower.hbs
  templates/item/sheets/trait.hbs
  templates/item/sheets/weapon.hbs
  templates/item/sheets/weaponUpgrade.hbs
Labels: tech debt

#383 Move actor templates
  module/helpers/templates.mjs
  templates/actor/parts/actor-alt-mode.hbs
  templates/actor/parts/actor-common.hbs
  templates/actor/parts/actor-vehicle-crew.hbs
  templates/actor/parts/headers/common.hbs
  templates/actor/parts/headers/gijoe.hbs
  templates/actor/parts/headers/header.hbs
  templates/actor/parts/headers/megaformZord.hbs
  templates/actor/parts/headers/npc.hbs
  templates/actor/parts/headers/pony.hbs
  templates/actor/parts/headers/pr.hbs
  templates/actor/parts/headers/transformer.hbs
  templates/actor/parts/headers/vehicle.hbs
  templates/actor/parts/headers/zord.hbs
  templates/actor/parts/items/altMode/container.hbs
  templates/actor/parts/items/armor/container.hbs
  templates/actor/parts/items/bond/container.hbs
  templates/actor/parts/items/classFeature/container.hbs
  templates/actor/parts/items/contact/container.hbs
  templates/actor/parts/items/feature/container.hbs
  templates/actor/parts/items/gear/container.hbs
  templates/actor/parts/items/hangUp/container.hbs
  templates/actor/parts/items/magicBauble/container.hbs
  templates/actor/parts/items/megaformTrait/container.hbs
  templates/actor/parts/items/origin/container.hbs
  templates/actor/parts/items/perk/container.hbs
  templates/actor/parts/items/power/container.hbs
  templates/actor/parts/items/spell/container.hbs
  templates/actor/parts/items/threatPower/container.hbs
  templates/actor/parts/items/trait/container.hbs
  templates/actor/parts/items/weapon/container.hbs
  templates/actor/parts/misc/accordion-skills.hbs
  templates/actor/parts/misc/active-effects.hbs
  templates/actor/parts/misc/background.hbs
  templates/actor/parts/misc/collapsible-item-container.hbs
  templates/actor/parts/misc/common.hbs
  templates/actor/parts/misc/defenses-pr.hbs
  templates/actor/parts/misc/defenses.hbs
  templates/actor/parts/misc/essence-skills.hbs
  templates/actor/parts/misc/health.hbs
  templates/actor/parts/misc/initiative.hbs
  templates/actor/parts/misc/mode-selector.hbs
  templates/actor/parts/misc/movement.hbs
  templates/actor/parts/misc/notes.hbs
  templates/actor/parts/misc/npc-defenses.hbs
  templates/actor/parts/misc/npc-essence-scores.hbs
  templates/actor/parts/misc/pc-skills.hbs
  templates/actor/parts/misc/spells.hbs
  templates/actor/parts/misc/stun.hbs
  templates/actor/parts/misc/vehicle-crew.hbs
  templates/actor/parts/misc/zord-common.hbs
  templates/actor/parts/misc/zordcombiner.hbs
  templates/actor/sheets/giJoe.hbs
  templates/actor/sheets/megaformZord.hbs
  templates/actor/sheets/npc.hbs
  templates/actor/sheets/pony.hbs
  templates/actor/sheets/powerRanger.hbs
  templates/actor/sheets/transformer.hbs
  templates/actor/sheets/vehicle.hbs
  templates/actor/sheets/zord.hbs
Labels: tech debt

#404 Rename `essenceSkills` to just `skills`
  lang/en.json
  module/dice.mjs
  module/dice.test.js
  module/helpers/config.mjs
  module/helpers/traits.mjs
  module/sheets/actor-sheet.mjs
  templates/actor/parts/items/weapon/details.hbs
  templates/actor/parts/misc/essence-skills.hbs
  templates/item/sheets/origin.hbs
  templates/item/sheets/weapon.hbs
Labels: tech debt

#407 Prelocalizing strings in config.mjs
  module/essence20.mjs
  module/helpers/config.mjs
  module/helpers/utils.mjs
  module/settings.js
  module/sheets/actor-sheet.mjs
  module/story-points-tracker.js
  templates/actor/parts/headers/common.hbs
  templates/actor/parts/headers/companion.hbs
  templates/actor/parts/headers/header.hbs
  templates/actor/parts/headers/transformer.hbs
  templates/actor/parts/items/armor/details.hbs
  templates/actor/parts/items/gear/details.hbs
  templates/actor/parts/items/magicBauble/details.hbs
  templates/actor/parts/items/perk/details.hbs
  templates/actor/parts/items/weapon/details.hbs
  templates/actor/parts/misc/accordion-skills.hbs
  templates/actor/parts/misc/defenses-pr.hbs
  templates/actor/parts/misc/defenses.hbs
  templates/actor/parts/misc/essence-skills.hbs
  templates/actor/parts/misc/initiative.hbs
  templates/actor/parts/misc/mode-selector.hbs
  templates/actor/parts/misc/movement.hbs
  templates/actor/parts/misc/npc-defenses.hbs
  templates/actor/parts/misc/npc-essence-scores.hbs
  templates/actor/parts/misc/pc-skills.hbs
  templates/actor/parts/misc/zord-common.hbs
  templates/item/sheets/altMode.hbs
  templates/item/sheets/armor.hbs
  templates/item/sheets/gear.hbs
  templates/item/sheets/magicBauble.hbs
  templates/item/sheets/origin.hbs
  templates/item/sheets/perk.hbs
  templates/item/sheets/spell.hbs
  templates/item/sheets/upgrade.hbs
  templates/item/sheets/weapon.hbs
Labels: tech debt
